In [19]:
import numpy as np
np.random.seed(0)

In [20]:
dataset_scale = 1
num_samples = 5
f = lambda x, y : (x * x) + (x * y) + (y * y) + 1

In [21]:
def get_random_dataset(function, samples, scale):
    array = np.random.rand(samples, 3) * scale
    array[...,2] = function(array[...,0], array[...,1])
    return array

In [22]:
dataset = get_random_dataset(f, num_samples, dataset_scale)

In [23]:
dataset

array([[0.5488135 , 0.71518937, 2.20519767],
       [0.54488318, 0.4236548 , 1.70722345],
       [0.43758721, 0.891773  , 2.37697011],
       [0.38344152, 0.79172504, 2.07743619],
       [0.56804456, 0.92559664, 2.7051839 ]])

In [24]:
x_train = dataset[...,[0,1]]

In [25]:
x_train

array([[0.5488135 , 0.71518937],
       [0.54488318, 0.4236548 ],
       [0.43758721, 0.891773  ],
       [0.38344152, 0.79172504],
       [0.56804456, 0.92559664]])

In [26]:
y_train = dataset[...,2]

In [27]:
y_train

array([2.20519767, 1.70722345, 2.37697011, 2.07743619, 2.7051839 ])

In [28]:
dataset = get_random_dataset(f, 100, 1)

In [53]:
train = dataset[:80]

In [54]:
test = dataset[80:]

In [55]:
train.shape

(80, 3)

In [56]:
test.shape

(20, 3)

In [58]:
x_train = train[...,[0,1]]

In [59]:
x_test = test[...,[0,1]]

In [60]:
y_train = train[...,2]

In [62]:
y_test = test[...,2]

array([1.35794107, 2.29169911, 1.0119766 , 2.5912402 , 1.38547118,
       3.58053781, 2.20110017, 3.27726826, 2.10642444, 1.39012557,
       2.13138372, 1.97439138, 1.80716739, 1.42646279, 3.52878948,
       3.12270901, 1.20545063, 1.02748588, 1.60273106, 1.02147789])